require('plugins')
require('theme')
require('plugins.airline')
require('plugins.gitgutter')
--require('plugins.tagbar') TODO: fix table setup in lua
require('plugins.rust_vim')
require('plugins.ultisnips')
require('plugins.vim-go')
require('plugins.vim-markdown')
require('mappings')
require('commands')
